export interface Product {
  id: string
  slug: string
  name: string
  category: string
  price: number
  image: string
  rating: number
  reviews: number
  description: string
  sizes?: string[]
  colors?: string[]
  inStock: boolean
  isFeatured?: boolean
  isHotDeal?: boolean
  discount?: number
}

export const products: Product[] = [
  {
    id: "1",
    slug: "pashmina-shawl-black",
    name: "Authentic Pashmina Shawl",
    category: "Textiles",
    price: 8500,
    image: "/black-pashmina-shawl-nepal.jpg",
    rating: 4.8,
    reviews: 142,
    description: "Hand-woven authentic pashmina shawl from Kashmir Valley. Soft, warm, and perfect for any occasion.",
    colors: ["Black", "Cream", "Burgundy"],
    inStock: true,
    isFeatured: true,
    isHotDeal: true,
    discount: 15,
  },
  {
    id: "2",
    slug: "kathmandu-thangka-painting",
    name: "Traditional Thangka Painting",
    category: "Art & Crafts",
    price: 12000,
    image: "/thangka-painting-nepal-art.jpg",
    rating: 4.9,
    reviews: 98,
    description: "Authentic hand-painted thangka artwork from Kathmandu Valley. Traditional Buddhist religious art.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "3",
    slug: "himalayan-spice-set",
    name: "Premium Himalayan Spice Set",
    category: "Spices & Food",
    price: 3200,
    image: "/himalayan-spices-collection.jpg",
    rating: 4.7,
    reviews: 256,
    description: "Curated collection of 8 premium Himalayan spices. Organic and freshly sourced.",
    inStock: true,
    isHotDeal: true,
    discount: 10,
  },
  {
    id: "4",
    slug: "hand-woven-carpet",
    name: "Hand-Woven Silk Carpet",
    category: "Home Decor",
    price: 45000,
    image: "/hand-woven-silk-carpet-nepal.jpg",
    rating: 4.9,
    reviews: 47,
    description: "Exquisite hand-woven silk carpet from Bhaktapur. 100% pure silk with natural dyes.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "5",
    slug: "kukri-knife-artisan",
    name: "Artisan Kukri Knife",
    category: "Tools & Equipment",
    price: 6500,
    image: "/traditional-kukri-knife-nepal.jpg",
    rating: 4.6,
    reviews: 189,
    description: "Authentic Gurkha-style kukri knife handcrafted by master artisans. High-quality steel.",
    inStock: true,
    isHotDeal: true,
    discount: 20,
  },
  {
    id: "6",
    slug: "nepali-prayer-beads",
    name: "Rudraksha Prayer Beads",
    category: "Spiritual Items",
    price: 2800,
    image: "/rudraksha-prayer-beads-mala.jpg",
    rating: 4.8,
    reviews: 324,
    description: "108 authentic rudraksha beads. Sacred and used for meditation and spiritual practices.",
    inStock: true,
  },
  {
    id: "7",
    slug: "kathmandu-pottery-set",
    name: "Bhaktapur Pottery Set",
    category: "Home Decor",
    price: 4500,
    image: "/traditional-nepal-pottery-set.jpg",
    rating: 4.7,
    reviews: 156,
    description: "Handmade ceramic pottery set from Bhaktapur. Each piece is unique and artisan-crafted.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "8",
    slug: "nepali-tea-sampler",
    name: "Darjeeling & Oolong Tea Sampler",
    category: "Spices & Food",
    price: 2200,
    image: "/darjeeling-oolong-tea-nepal.jpg",
    rating: 4.9,
    reviews: 412,
    description: "Premium tea selection including Darjeeling and Himalayan oolong. 4 varieties included.",
    inStock: true,
    isHotDeal: true,
    discount: 12,
  },
  {
    id: "9",
    slug: "dhaka-fabric-scarf",
    name: "Traditional Dhaka Fabric Scarf",
    category: "Textiles",
    price: 1800,
    image: "/dhaka-fabric-scarf-nepal-traditional.jpg",
    rating: 4.6,
    reviews: 287,
    description: "Hand-loomed dhaka fabric scarf with traditional geometric patterns.",
    inStock: true,
  },
  {
    id: "10",
    slug: "singing-bowl-set",
    name: "Handmade Singing Bowl Set",
    category: "Spiritual Items",
    price: 5800,
    image: "/singing-bowl-meditation-nepal.jpg",
    rating: 4.8,
    reviews: 203,
    description: "Set of 3 handmade singing bowls. Used for meditation, yoga, and sound therapy.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "11",
    slug: "lokta-paper-stationery",
    name: "Lokta Paper Stationery Set",
    category: "Art & Crafts",
    price: 1500,
    image: "/lokta-paper-nepal-handmade-stationery.jpg",
    rating: 4.7,
    reviews: 178,
    description: "Eco-friendly handmade lokta paper products. Includes notebook, cards, and envelopes.",
    inStock: true,
  },
  {
    id: "12",
    slug: "nepali-wool-sweater",
    name: "Wool Yak Sweater",
    category: "Textiles",
    price: 4200,
    image: "/yak-wool-sweater-nepal-warm.jpg",
    rating: 4.7,
    reviews: 94,
    description: "Cozy hand-knit yak wool sweater. Extremely warm and comfortable for mountain climates.",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "13",
    slug: "mandir-brass-statue",
    name: "Brass Lord Krishna Statue",
    category: "Spiritual Items",
    price: 3800,
    image: "/brass-krishna-statue-nepal-spiritual.jpg",
    rating: 4.9,
    reviews: 167,
    description: "Intricately cast brass statue of Lord Krishna. Hand-finished with traditional methods.",
    inStock: true,
  },
  {
    id: "14",
    slug: "himalayan-honey-raw",
    name: "Raw Himalayan Honey",
    category: "Spices & Food",
    price: 1200,
    image: "/raw-himalayan-honey-nepal-pure.jpg",
    rating: 4.8,
    reviews: 521,
    description: "Pure raw honey from high altitude Himalayan regions. Unprocessed and organic.",
    inStock: true,
    isHotDeal: true,
    discount: 8,
  },
  {
    id: "15",
    slug: "thamel-backpacker-bag",
    name: "Handwoven Nepali Backpack",
    category: "Travel",
    price: 3500,
    image: "/nepali-handwoven-backpack-travel.jpg",
    rating: 4.6,
    reviews: 243,
    description: "Durable handwoven backpack perfect for travel. Made from recycled cotton and hemp.",
    inStock: true,
  },
  {
    id: "16",
    slug: "mustang-blanket",
    name: "Mustang Yak Wool Blanket",
    category: "Textiles",
    price: 7800,
    image: "/mustang-yak-wool-blanket.png",
    rating: 4.9,
    reviews: 76,
    description: "Premium yak wool blanket from Mustang region. Super soft and luxuriously warm.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "17",
    slug: "wood-carved-mask",
    name: "Hand-Carved Wooden Mask",
    category: "Art & Crafts",
    price: 2600,
    image: "/hand-carved-wooden-mask.png",
    rating: 4.7,
    reviews: 112,
    description: "Traditional ceremonial mask hand-carved from wood. Each mask is unique.",
    inStock: true,
  },
  {
    id: "18",
    slug: "saffron-threads-premium",
    name: "Premium Kashmiri Saffron",
    category: "Spices & Food",
    price: 4800,
    image: "/premium-kashmiri-saffron.png",
    rating: 4.9,
    reviews: 89,
    description: "Grade A Kashmiri saffron. Premium quality with intense color and aroma.",
    inStock: true,
    isHotDeal: true,
    discount: 5,
  },
  {
    id: "19",
    slug: "prayer-flag-set",
    name: "Tibetan Prayer Flag Set",
    category: "Spiritual Items",
    price: 1400,
    image: "/tibetan-prayer-flag-set.png",
    rating: 4.8,
    reviews: 267,
    description: "Colorful traditional prayer flags. Handprinted with sacred mantras.",
    inStock: true,
  },
  {
    id: "20",
    slug: "chitrakar-painting",
    name: "Chitrakar Scroll Painting",
    category: "Art & Crafts",
    price: 6200,
    image: "/chitrakar-scroll-painting.png",
    rating: 4.8,
    reviews: 78,
    description: "Traditional scroll painting by local chitrakar artists. Historical narrative style.",
    inStock: true,
  },
  {
    id: "21",
    slug: "copper-water-vessel",
    name: "Copper Water Pitcher",
    category: "Home Decor",
    price: 1900,
    image: "/copper-water-pitcher.png",
    rating: 4.6,
    reviews: 134,
    description: "Hand-hammered copper water pitcher. Eco-friendly and health-promoting.",
    inStock: true,
  },
  {
    id: "22",
    slug: "tibetan-bell-dorje",
    name: "Tibetan Bell & Dorje Set",
    category: "Spiritual Items",
    price: 3200,
    image: "/tibetan-bell-dorje-set.png",
    rating: 4.9,
    reviews: 145,
    description: "Hand-cast bronze bell and dorje. Used in Buddhist rituals and meditation.",
    inStock: true,
  },
  {
    id: "23",
    slug: "jute-craft-basket",
    name: "Eco-Friendly Jute Basket",
    category: "Home Decor",
    price: 2100,
    image: "/eco-friendly-jute-basket.png",
    rating: 4.7,
    reviews: 198,
    description: "Handwoven jute basket. Perfect for storage and environmentally sustainable.",
    inStock: true,
  },
  {
    id: "24",
    slug: "momo-maker-kit",
    name: "Nepali Momo Maker Kit",
    category: "Kitchen",
    price: 2800,
    image: "/nepali-momo-maker-kit.png",
    rating: 4.6,
    reviews: 156,
    description: "Complete set for making traditional Nepali momos. Includes tools and recipe guide.",
    inStock: true,
  },
  {
    id: "25",
    slug: "khipu-replica-incense",
    name: "Khipu Stick Incense Bundle",
    category: "Spiritual Items",
    price: 980,
    image: "/khipu-stick-incense-bundle.png",
    rating: 4.8,
    reviews: 267,
    description: "Traditional hand-rolled incense sticks. Made from natural himalayan herbs.",
    inStock: true,
  },
  {
    id: "26",
    slug: "stone-carved-ornament",
    name: "Stone Carved Decorative Ornament",
    category: "Home Decor",
    price: 3400,
    image: "/stone-carved-decorative-ornament.png",
    rating: 4.7,
    reviews: 89,
    description: "Hand-carved stone ornament. Beautiful addition to home or garden.",
    inStock: true,
  },
  {
    id: "27",
    slug: "silk-ribbon-bookmark",
    name: "Silk Ribbon Bookmark Set",
    category: "Art & Crafts",
    price: 1100,
    image: "/silk-ribbon-bookmark-set.png",
    rating: 4.8,
    reviews: 178,
    description: "Set of 5 handmade silk ribbon bookmarks with traditional patterns.",
    inStock: true,
  },
  {
    id: "28",
    slug: "indigo-dyed-fabric",
    name: "Indigo-Dyed Cotton Fabric",
    category: "Textiles",
    price: 2400,
    image: "/indigo-dyed-cotton-fabric.png",
    rating: 4.7,
    reviews: 123,
    description: "Hand-dyed indigo cotton fabric. Perfect for crafts or traditional wear.",
    inStock: true,
  },
  {
    id: "29",
    slug: "brass-oil-lamp",
    name: "Brass Diya Oil Lamp",
    category: "Home Decor",
    price: 1600,
    image: "/brass-diya-oil-lamp.jpg",
    rating: 4.6,
    reviews: 167,
    description: "Traditional brass diya lamp. Perfect for festivals and daily worship.",
    inStock: true,
  },
  {
    id: "30",
    slug: "macrame-wall-hanging",
    name: "Handmade Macrame Wall Hanging",
    category: "Home Decor",
    price: 3100,
    image: "/handmade-macrame-wall-hanging.png",
    rating: 4.8,
    reviews: 145,
    description: "Bohemian macrame wall hanging. Made from natural cotton cord.",
    inStock: true,
  },
]
